### ISSUE TITLE
Elytra and Cape don't connect to the player Model correctly (Possible Essential Mod Incompatibility)

### ISSUE THREAD

**Issue by GeradesoLukas** [nvb-uy/Animation_Overhaul#10]
Hello, I just tried out the mod and I love it. However i have noticed, that the elytra feature and the cape feature are not rendered properly. They don't move with the body model part.

I am using the essential mod too, maybe that might be an issue. However other essential cosmetics connect correctly

![image](https://github.com/nvb-uy/Animation_Overhaul/assets/59490449/e0849d15-7ddb-4153-9473-83c07c51a2b4)
![image](https://github.com/nvb-uy/Animation_Overhaul/assets/59490449/da965aee-6b87-4c3a-8158-b40ffcf83c35)

**Comment by GeradesoLukas** [comment]
Oh and essential emotes are completely bugged xD

A Possible fix would be to disable the animations when essential does its thing

**Comment by nvb-uy** [comment]
Not planning on supporting essential currently, it's a closed source and very invasive mod
