### ISSUE TITLE
Compatibility with Personality mod

### ISSUE THREAD

**Issue by Tuna7822** [nvb-uy/Animation_Overhaul#2]
Please fix the bug that breaks the animation while the player is “sitting”. The player falls halfway through the ground, instead of displaying “sitting” on the surface.

**Comment by nvb-uy** [comment]
Fixed on 1.3.0

https://modrinth.com/mod/animationoverhaul/versions

**Comment by Lictor000** [comment]
Hey, this seems to not be fixed on the 1.19.2 forge version of the mod. Tested both 1.3.0 and 1.3.1, with Personality being the only other mod installed.
