### ISSUE TITLE
Stdout Spam when Mod is Loaded and In Minecraft World

### ISSUE THREAD

**Issue by InputandOutput** [nvb-uy/Animation_Overhaul#24]
Hello Nicole, 
I discovered an STDOUT spam bug when playing around with Animation Overhaul; the message produced is: "[STDOUT]: RIGHT". The message spams more than 15 times per second, and the issue resolves itself when Animation Overhaul is not enabled for loading. Please let me know if you are able to replicate the bug or need anything from me to fix the bug. 

Many thanks.

**Comment by nvb-uy** [comment]
This has been fixed on the latest version
