### ISSUE TITLE
Port to 1.21.x

### ISSUE THREAD

**Issue by D-Maxwell** [nvb-uy/Animation_Overhaul#28]
hello there ;

are there any plans for a 1.21 port of this wonderful mod ?

I would be glad to include this in the latest release of my Mendeleev modpack.

**Comment by nvb-uy** [comment]
The required dependencies aren't even on 1.21, so not yet no

**Comment by vorlie** [comment]
@nvb-uy If you meant "[Necronomicon](https://modrinth.com/mod/necronomicon/)". then they released a 1.21 version a few weeks ago.

**Comment by nvb-uy** [comment]
> @nvb-uy If you meant "[Necronomicon](https://modrinth.com/mod/necronomicon/)". then they released a 1.21 version a few weeks ago.

Oh no, Necronomicon is my API so I'm well aware as I updated it haha, I'm talking about Player Animator API, which 20 hours ago updated to 1.21, so I'll be updating this mod soonish

**Comment by vorlie** [comment]
Ahh, I didn't noticed that haha.

**Comment by vorlie** [comment]
> > @nvb-uy If you meant "[Necronomicon](https://modrinth.com/mod/necronomicon/)". then they released a 1.21 version a few weeks ago.
> 
> Oh no, Necronomicon is my API so I'm well aware as I updated it haha, I'm talking about Player Animator API, which 20 hours ago updated to 1.21, so I'll be updating this mod soonish

Umm. so how's the progress on update for 1.21
