### ISSUE TITLE
Bewitchment Compatibility

### ISSUE THREAD

**Issue by jusinnnn** [nvb-uy/Animation_Overhaul#3]
It seems this mod is not compatibile with bewitchment, specifically the Specter Bangle, as crouching doesn't make you invisible to other players.

**Comment by jusinnnn** [comment]
i've found a couple more things not compatible with bewitchment. being a werewolf still has you in your human form even when you transform, animation when riding the broom are weird. i haven't been able to test anything else, but i imagine vampire bat would also be broken

**Comment by nvb-uy** [comment]
Fixed on 1.3.0

https://modrinth.com/mod/animationoverhaul/versions
