### ISSUE TITLE
1.21 support question and a thank you

### ISSUE THREAD

**Issue by WhyAreLess** [nvb-uy/Animation_Overhaul#30]
I'm not too sure how Github works with labels that I tried to add but couldn't figure out how!

Will there be 1.21 support in the future when Better Combat eventually supports it?

And also thank you for making this Animation Overhaul! 
I finally could clean up a little where I removed 4-5 animations and libraries and now I only use yours as it's all I've ever wanted! 

Thank you very much!

**Comment by nvb-uy** [comment]
Hi, this mod has nothing to do with better combat, but it requires playerAnimator which yet hasn't been updated to 1.21, so until it updates I can't really update this mod

**Comment by zombieloke** [comment]
> Hi, this mod has nothing to do with better combat, but it requires playerAnimator which yet hasn't been updated to 1.21, so until it updates I can't really update this mod

its updated
