### ISSUE TITLE
Bring Third Person Lantern Holding animation back

### ISSUE THREAD

**Issue by Dente222** [nvb-uy/Animation_Overhaul#31]
It is not an issue or incompatibility but it just looks weird that while in First Person you hold lantern properly
you dont do it in third person tho :L

So my question is if it would be possible to make it look like it is holding it  the same way as it does in first person? :)

![image](https://github.com/user-attachments/assets/226416e2-c046-4412-be68-bd22af0b4210)

**Comment by nvb-uy** [comment]
Animation Overhaul doesn't touch the lantern, and this is not how it looks in vanilla so this is caused by another mod
