### ISSUE TITLE
different  jump animation please 

### ISSUE THREAD

**Issue by Galaxy1133** [nvb-uy/Animation_Overhaul#39]
ok look i love everything about this mod the only thing im asking you to change is the jump i do not know why but it hurts me when i see it jump can you make it look more like a jump then someone jumping in there air exited  different and i do not know how to make animations or textures

**Comment by nvb-uy** [comment]
As stated in the description, the mod is customizable and you can change the animation with a resourcepack. Alternatively, you can simply disable the animation in the config.

**Comment by Artyx1** [comment]
> As stated in the description, the mod is customizable and you can change the animation with a resourcepack. Alternatively, you can simply disable the animation in the config.

hey sorry if this is a stupid question (probably bc im a stupid guy) but where is the config, i cant seem to find it in the settings
