### ISSUE TITLE
weird jump animation and the cloak is not attached to the body

### ISSUE THREAD

**Issue by 4lesArt** [nvb-uy/Animation_Overhaul#4]
please edit the jump animation, it looks weird when you jump running
also, the cloak is not attached to the player's body and some animations look stupid because of this

**Comment by nvb-uy** [comment]
Could you elaborate on "weird when jump running"? A video would help, as it might just be a bug.

If you don't like the animation you can edit it yourself, AO is resourcepack compatible :)

**Comment by elislavkat** [comment]
hello.
mod [https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks](url)
have backpaks on the back bone. that bone do not move when player digging with pickaxe

**Comment by 4lesArt** [comment]
https://youtu.be/LROi3nONgpo
this is a link to the video with the problem

**Comment by nvb-uy** [comment]
There's no bending happening at all. If you don't like the animation feel free to change it using a resource pack.

The cape issue is a known bug, which might be caused by playerAnimator itself

**Comment by 4lesArt** [comment]
Okay, then what can I use to make my animation?

**Comment by nvb-uy** [comment]
Blockbench using the GeckoLib/AzureLib animation plugin, you can edit the animations from assets/animation_overhaul/player_animations
