### ISSUE TITLE
Cool mod, but...

### ISSUE THREAD

**Issue by BlueYoshi68** [nvb-uy/Animation_Overhaul#44]
How the hell do you advertise "make your own animations!" and then not show anyone how to do it....what even is the point at that rate.

**Comment by nvb-uy** [comment]
It's explained in the pinned messages of the linked discord's elocin projects channel. If you have basic resourcepack knowledge you can also check the assets folder inside the mod to see how it works. They're simple geckolib JSON animations, you can import the json files with blockbench and edit them as you'd like. Just make sure you ship the MIT License that comes with Kevin's animations if you use them as a base.
