### ISSUE TITLE
Customizable Player Models is not working with Animation Overhaul

### ISSUE THREAD

**Issue by src3453** [nvb-uy/Animation_Overhaul#5]
in third-person view, custom models wont be rendered

**Comment by nvb-uy** [comment]
Should be fixed on 1.3.0, working on it currently :)

**Comment by nvb-uy** [comment]
Fixed on 1.3.0

https://modrinth.com/mod/animationoverhaul/versions

**Comment by src3453** [comment]
Thanks! ✨
