### ISSUE TITLE
Add config to disable all animations on holding specific item.

### ISSUE THREAD

**Issue by SwearAmber** [nvb-uy/Animation_Overhaul#53]
Hi, love the mod, wanted to know if there's some secret setting to disable all or specific animations when u hold specific item, this because the render seems off the limits as I will show on the video:

Some things I noticed:

- Some custom holding items, like the video, doesn't match, this can be because mods compatibility but, if the animation can be disabled when holding that specific item, that should work fine.
- On some animations, the fade option doesn't work, it keeps playing it.

https://github.com/user-attachments/assets/23fe883b-4dbf-490a-a030-e3ec77195f30

**Comment by nvb-uy** [comment]
Will add this along other useful configs. Currently on holidays and I didn't notice all these issues due to notifications off. Thanks for reporting!

**Comment by SwearAmber** [comment]
¿Did you had the time to add that config? I'm using the 1.20.1 last version, but maybe there's a new branch that is not on curseforge.
