### ISSUE TITLE
Better Combat Third Person Weapon Holding Animations Conflict

### ISSUE THREAD

**Issue by CravenCraft** [nvb-uy/Animation_Overhaul#6]
Hey, love the mod! Noticed an issue with Better Combat in that the custom animations that they have for holding weapons (such as two handed ones) are overwritten by your mod. I know you mentioned that compatibility with that mod is a key feature that you want in this mod, so I figured that you'd want to know about this and maybe add a config option to allow their animations to override this mods.

**Comment by rjshadowface** [comment]
When I disable the "sword_swing" anymation via the config file the Better Combat anymations work as normal.

**Comment by CravenCraft** [comment]
Sorry, I meant the **holding** animations. Not the swinging animations. Those work fine. 

For example, in third person the player doesn't hold a two-handed weapon with two hands, but with just one.

**Comment by nvb-uy** [comment]
Fixed on 1.3.0 ! Will close on release as it isn't released yet

**Comment by nvb-uy** [comment]
Fixed on 1.3.0

https://modrinth.com/mod/animationoverhaul/versions
