### ISSUE TITLE
Incompatibility with Cosmetic Armor Reworked

### ISSUE THREAD

**Issue by sumire0nekoneko** [nvb-uy/Animation_Overhaul#7]
Armour transparency in Cosmetic Armor Reworked does not work when using this mod.
Versions include.

CosmeticArmorReworked-1.19.2-v1a.jar
Animation_Overhaul-forge-1.19.x-1.2.0.jar

**Comment by nvb-uy** [comment]
Fixed on 1.3.0 (not released yet) will close on release

**Comment by nvb-uy** [comment]
Fixed on 1.3.0

https://modrinth.com/mod/animationoverhaul/versions
