### ISSUE TITLE
Config File Not Working

### ISSUE THREAD

**Issue by rjshadowface** [nvb-uy/Animation_Overhaul#8]
Verry weard anymation when using tools (axe, pick axe etc.) to mine trees, ground etc. When I disable the punching animation in the config it does not revert to the Minecraft default animation for mining it just completley removed any animation related to mining.

I also tried disabling other animations via your config file and they disable even the MC default animations for sneaking and jumping. I wanted to try your mode with Salty's SimplySneak, but when your sneaking is disabled and the other mod is enabled there is no sneaking anymation whatsoever.

Interestingly enough when I disable the jumping anymation in your mod and enable Salty's JumpAnimation its jumping anymation works, but its falling anymation doesn't even with yours disabled.

**Comment by nvb-uy** [comment]
Looking into it for 1.3.0 :)

**Comment by nvb-uy** [comment]
Fixed on 1.3.0

https://modrinth.com/mod/animationoverhaul/versions
