### ISSUE TITLE
Swimming Anymation Broken

### ISSUE THREAD

**Issue by rjshadowface** [nvb-uy/Animation_Overhaul#9]
Swimming does not work as it should. When I try to swim with forward key walking anymation plays. When I try to swim with ctrl+forward key in open water i.e. only water blocks around player it plays the running anymation instead of the swiming anymation. When I swim (ctrl+forward key) close to the bottom (i.e. bellow plays sand or other solid blocks) then the swimming anymaiton plays. When I am hovering in water or just slowly descending in the water (or try to assend with space key) the player stands still (no anymation) but when hovering above water it start paying the anymation showing like he is in the water.

**Comment by nvb-uy** [comment]
Looking into it for 1.3.0 :)

**Comment by nvb-uy** [comment]
Fixed on 1.3.0

https://modrinth.com/mod/animationoverhaul/versions
